name = "shotbyhamadi-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "shotbyhamadi_db"
database_name = "shotbyhamadi-db"
database_id = "7cab0c9a-266b-413a-8885-0eff322ae53c"