export const runtime = "edge";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "R2 Storage Reference — ShotByHamadi",
    description: "Cloudflare R2 object storage architecture and naming conventions.",
};

const buckets = [
    {
        name: "ShotByHamadi Assets",
        type: "Public Bucket",
        description: "Hosts public portfolio images and website structural assets (logos, placeholders). Assets are globally cached and delivered via a custom public R2 domain.",
        prefixes: [
            { path: "/portfolio/sports/", desc: "Public sports photography." },
            { path: "/portfolio/portraits/", desc: "Public portrait photography." },
            { path: "/portfolio/events/", desc: "Public event photography." },
            { path: "/system/", desc: "Logos, watermarks, UI elements." },
        ],
    },
    {
        name: "ShotByHamadi Vault",
        type: "Private Bucket",
        description: "Hosts raw, uncompressed, high-resolution client assets. Accessed strictly via pre-signed URLs generated by the worker, ensuring secure delivery directly to authenticated Client Portals.",
        prefixes: [
            { path: "/clients/[project_id]/raw/", desc: "Original unedited files (strictly internal)." },
            { path: "/clients/[project_id]/deliverables/", desc: "Final edited files served to the Client Portal." },
            { path: "/clients/[project_id]/web_proxies/", desc: "Highly compressed JPGs for fast gallery loading." },
        ],
    }
];

export default function StorageDocsPage() {
    return (
        <div>
            {/* Header */}
            <div className="mb-12 border-b border-zinc-900 pb-10">
                <div className="flex items-center gap-4 mb-3">
                    <p className="font-mono text-[9px] tracking-[0.4em] text-zinc-600 uppercase">03_DATABASE / R2 Storage</p>
                    <span className="text-[9px] font-mono uppercase tracking-widest text-[#A1A1AA] border border-zinc-800 bg-zinc-900/20 px-2 py-0.5">Object Storage</span>
                </div>
                <h1 className="text-4xl font-light tracking-[0.12em] uppercase text-white mb-4">
                    R2 Storage Reference
                </h1>
                <p className="text-zinc-400 text-sm leading-relaxed max-w-2xl mt-4">
                    Media assets are distributed using Cloudflare R2, providing zero-egress-fee, highly durable object storage.
                    This establishes how buckets and object prefixes are structured to separate public portfolio caching from secure client asset delivery.
                </p>
            </div>

            {/* Content Sections */}
            <div className="flex flex-col gap-16">
                {buckets.map((bucket) => (
                    <div key={bucket.name} className="scroll-mt-28">
                        <div className="flex items-center justify-between mb-4">
                            <h2 className="text-2xl font-light tracking-[0.1em] text-white">
                                {bucket.name}
                            </h2>
                            <span className="text-[10px] tracking-widest uppercase font-mono px-3 py-1 border border-zinc-900 text-zinc-500">
                                {bucket.type}
                            </span>
                        </div>
                        <p className="text-sm text-zinc-400 mb-8 leading-relaxed max-w-3xl">
                            {bucket.description}
                        </p>

                        <div className="flex flex-col border border-zinc-900 bg-[#0a0a0a]">
                            <div className="grid grid-cols-[1fr_2fr] border-b border-zinc-900 bg-black/40 px-6 py-4">
                                <span className="text-[10px] tracking-widest uppercase text-zinc-600 font-mono">Prefix Path</span>
                                <span className="text-[10px] tracking-widest uppercase text-zinc-600 font-mono">Usage</span>
                            </div>
                            {bucket.prefixes.map((prefix, i) => (
                                <div key={i} className="grid grid-cols-1 md:grid-cols-[1fr_2fr] gap-4 px-6 py-4 border-b border-zinc-900/50 last:border-b-0 hover:bg-zinc-900/30 transition-colors">
                                    <div className="font-mono text-xs text-[#A1A1AA]">
                                        {prefix.path}
                                    </div>
                                    <div className="text-sm text-zinc-400">
                                        {prefix.desc}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
